// app/layout.tsx
import type { Metadata } from 'next';
import '../styles/globals.css';
import Navbar from '@/components/layout/Navbar';
import ClientProviders from './ClientProvider';
import AuthInitializer from './AuthInitializer'; // 👈 lo agregás
import InactivityHandler from './InactivityHandler';


export const metadata: Metadata = {
  title: 'DOZZZE',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="es">
      <body className="antialiased">
        <ClientProviders>
          <AuthInitializer />
          <InactivityHandler />
          <Navbar />
          {children}
        </ClientProviders>
      </body>
    </html>
  );
}
